# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sat May 25 18:44:30 2013
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(600, 450)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.MsgLbl = QtGui.QLabel(self.centralWidget)
        self.MsgLbl.setGeometry(QtCore.QRect(10, 260, 62, 16))
        self.MsgLbl.setObjectName(_fromUtf8("MsgLbl"))
        self.line = QtGui.QFrame(self.centralWidget)
        self.line.setGeometry(QtCore.QRect(130, 240, 361, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.FichierGroup = QtGui.QGroupBox(self.centralWidget)
        self.FichierGroup.setEnabled(True)
        self.FichierGroup.setGeometry(QtCore.QRect(10, 0, 221, 91))
        self.FichierGroup.setObjectName(_fromUtf8("FichierGroup"))
        self.TrainBtn = QtGui.QPushButton(self.FichierGroup)
        self.TrainBtn.setGeometry(QtCore.QRect(90, 20, 114, 32))
        self.TrainBtn.setObjectName(_fromUtf8("TrainBtn"))
        self.TestBtn = QtGui.QPushButton(self.FichierGroup)
        self.TestBtn.setEnabled(False)
        self.TestBtn.setGeometry(QtCore.QRect(90, 50, 114, 32))
        self.TestBtn.setObjectName(_fromUtf8("TestBtn"))
        self.TestLbl = QtGui.QLabel(self.FichierGroup)
        self.TestLbl.setGeometry(QtCore.QRect(10, 60, 62, 16))
        self.TestLbl.setObjectName(_fromUtf8("TestLbl"))
        self.TrainLbl = QtGui.QLabel(self.FichierGroup)
        self.TrainLbl.setGeometry(QtCore.QRect(10, 30, 62, 16))
        self.TrainLbl.setObjectName(_fromUtf8("TrainLbl"))
        self.MsgScrollArea = QtGui.QScrollArea(self.centralWidget)
        self.MsgScrollArea.setGeometry(QtCore.QRect(10, 280, 581, 131))
        self.MsgScrollArea.setWidgetResizable(True)
        self.MsgScrollArea.setObjectName(_fromUtf8("MsgScrollArea"))
        self.MsgScrl = QtGui.QWidget()
        self.MsgScrl.setGeometry(QtCore.QRect(0, 0, 579, 129))
        self.MsgScrl.setObjectName(_fromUtf8("MsgScrl"))
        self.MsgTxt = QtGui.QTextBrowser(self.MsgScrl)
        self.MsgTxt.setGeometry(QtCore.QRect(0, 0, 581, 131))
        self.MsgTxt.setObjectName(_fromUtf8("MsgTxt"))
        self.MsgScrollArea.setWidget(self.MsgScrl)
        self.TraceBox = QtGui.QGroupBox(self.centralWidget)
        self.TraceBox.setEnabled(False)
        self.TraceBox.setGeometry(QtCore.QRect(10, 90, 221, 91))
        self.TraceBox.setObjectName(_fromUtf8("TraceBox"))
        self.TraceMinTxt = QtGui.QLineEdit(self.TraceBox)
        self.TraceMinTxt.setGeometry(QtCore.QRect(40, 30, 51, 21))
        self.TraceMinTxt.setInputMask(_fromUtf8(""))
        self.TraceMinTxt.setAlignment(QtCore.Qt.AlignCenter)
        self.TraceMinTxt.setObjectName(_fromUtf8("TraceMinTxt"))
        self.TraceMinLbl = QtGui.QLabel(self.TraceBox)
        self.TraceMinLbl.setGeometry(QtCore.QRect(10, 30, 31, 16))
        self.TraceMinLbl.setObjectName(_fromUtf8("TraceMinLbl"))
        self.TraceMaxLbl = QtGui.QLabel(self.TraceBox)
        self.TraceMaxLbl.setGeometry(QtCore.QRect(10, 60, 31, 16))
        self.TraceMaxLbl.setObjectName(_fromUtf8("TraceMaxLbl"))
        self.TraceMaxTxt = QtGui.QLineEdit(self.TraceBox)
        self.TraceMaxTxt.setGeometry(QtCore.QRect(40, 60, 51, 21))
        self.TraceMaxTxt.setInputMask(_fromUtf8(""))
        self.TraceMaxTxt.setAlignment(QtCore.Qt.AlignCenter)
        self.TraceMaxTxt.setObjectName(_fromUtf8("TraceMaxTxt"))
        self.TracePasLbl = QtGui.QLabel(self.TraceBox)
        self.TracePasLbl.setGeometry(QtCore.QRect(120, 30, 31, 16))
        self.TracePasLbl.setObjectName(_fromUtf8("TracePasLbl"))
        self.TracePasTxt = QtGui.QLineEdit(self.TraceBox)
        self.TracePasTxt.setGeometry(QtCore.QRect(150, 30, 51, 21))
        self.TracePasTxt.setInputMask(_fromUtf8(""))
        self.TracePasTxt.setAlignment(QtCore.Qt.AlignCenter)
        self.TracePasTxt.setObjectName(_fromUtf8("TracePasTxt"))
        self.TraceBtn = QtGui.QPushButton(self.TraceBox)
        self.TraceBtn.setGeometry(QtCore.QRect(110, 50, 101, 32))
        self.TraceBtn.setObjectName(_fromUtf8("TraceBtn"))
        self.LogTraceBox = QtGui.QGroupBox(self.centralWidget)
        self.LogTraceBox.setEnabled(False)
        self.LogTraceBox.setGeometry(QtCore.QRect(10, 180, 221, 61))
        self.LogTraceBox.setObjectName(_fromUtf8("LogTraceBox"))
        self.LTBtn = QtGui.QPushButton(self.LogTraceBox)
        self.LTBtn.setGeometry(QtCore.QRect(110, 20, 101, 32))
        self.LTBtn.setObjectName(_fromUtf8("LTBtn"))
        self.LTDixPuisTxt = QtGui.QLineEdit(self.LogTraceBox)
        self.LTDixPuisTxt.setGeometry(QtCore.QRect(40, 30, 51, 21))
        self.LTDixPuisTxt.setInputMask(_fromUtf8(""))
        self.LTDixPuisTxt.setAlignment(QtCore.Qt.AlignCenter)
        self.LTDixPuisTxt.setObjectName(_fromUtf8("LTDixPuisTxt"))
        self.LTdixPuisLbl = QtGui.QLabel(self.LogTraceBox)
        self.LTdixPuisLbl.setGeometry(QtCore.QRect(10, 30, 31, 16))
        self.LTdixPuisLbl.setObjectName(_fromUtf8("LTdixPuisLbl"))
        self.modeleBox = QtGui.QGroupBox(self.centralWidget)
        self.modeleBox.setEnabled(False)
        self.modeleBox.setGeometry(QtCore.QRect(240, 0, 341, 181))
        self.modeleBox.setObjectName(_fromUtf8("modeleBox"))
        self.PredefBRBtn = QtGui.QRadioButton(self.modeleBox)
        self.PredefBRBtn.setGeometry(QtCore.QRect(10, 30, 151, 20))
        self.PredefBRBtn.setChecked(False)
        self.PredefBRBtn.setObjectName(_fromUtf8("PredefBRBtn"))
        self.OptimiseBRBtn = QtGui.QRadioButton(self.modeleBox)
        self.OptimiseBRBtn.setGeometry(QtCore.QRect(10, 70, 102, 20))
        self.OptimiseBRBtn.setChecked(True)
        self.OptimiseBRBtn.setObjectName(_fromUtf8("OptimiseBRBtn"))
        self.BTxt = QtGui.QLineEdit(self.modeleBox)
        self.BTxt.setGeometry(QtCore.QRect(172, 30, 111, 21))
        self.BTxt.setAlignment(QtCore.Qt.AlignCenter)
        self.BTxt.setObjectName(_fromUtf8("BTxt"))
        self.label_5 = QtGui.QLabel(self.modeleBox)
        self.label_5.setGeometry(QtCore.QRect(120, 100, 31, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.modeleBox)
        self.label_6.setGeometry(QtCore.QRect(20, 100, 31, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.BMinTxt = QtGui.QLineEdit(self.modeleBox)
        self.BMinTxt.setGeometry(QtCore.QRect(50, 100, 51, 21))
        self.BMinTxt.setInputMask(_fromUtf8(""))
        self.BMinTxt.setAlignment(QtCore.Qt.AlignCenter)
        self.BMinTxt.setObjectName(_fromUtf8("BMinTxt"))
        self.BMaxTxt = QtGui.QLineEdit(self.modeleBox)
        self.BMaxTxt.setGeometry(QtCore.QRect(150, 100, 51, 21))
        self.BMaxTxt.setInputMask(_fromUtf8(""))
        self.BMaxTxt.setAlignment(QtCore.Qt.AlignCenter)
        self.BMaxTxt.setObjectName(_fromUtf8("BMaxTxt"))
        self.IntervalTxt = QtGui.QLineEdit(self.modeleBox)
        self.IntervalTxt.setGeometry(QtCore.QRect(250, 100, 51, 21))
        self.IntervalTxt.setInputMask(_fromUtf8(""))
        self.IntervalTxt.setAlignment(QtCore.Qt.AlignCenter)
        self.IntervalTxt.setObjectName(_fromUtf8("IntervalTxt"))
        self.label_7 = QtGui.QLabel(self.modeleBox)
        self.label_7.setGeometry(QtCore.QRect(220, 100, 31, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.line_2 = QtGui.QFrame(self.modeleBox)
        self.line_2.setGeometry(QtCore.QRect(120, 60, 118, 3))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(self.modeleBox)
        self.line_3.setGeometry(QtCore.QRect(120, 130, 118, 3))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.ModelBtn = QtGui.QPushButton(self.modeleBox)
        self.ModelBtn.setGeometry(QtCore.QRect(0, 140, 114, 32))
        self.ModelBtn.setObjectName(_fromUtf8("ModelBtn"))
        self.ResBtn = QtGui.QPushButton(self.modeleBox)
        self.ResBtn.setEnabled(False)
        self.ResBtn.setGeometry(QtCore.QRect(230, 140, 114, 32))
        self.ResBtn.setObjectName(_fromUtf8("ResBtn"))
        self.statsBtn = QtGui.QPushButton(self.modeleBox)
        self.statsBtn.setEnabled(False)
        self.statsBtn.setGeometry(QtCore.QRect(120, 140, 114, 32))
        self.statsBtn.setObjectName(_fromUtf8("statsBtn"))
        self.ClearBtn = QtGui.QPushButton(self.centralWidget)
        self.ClearBtn.setGeometry(QtCore.QRect(510, 250, 81, 32))
        self.ClearBtn.setObjectName(_fromUtf8("ClearBtn"))
        self.PredBox = QtGui.QGroupBox(self.centralWidget)
        self.PredBox.setEnabled(False)
        self.PredBox.setGeometry(QtCore.QRect(250, 180, 321, 61))
        self.PredBox.setObjectName(_fromUtf8("PredBox"))
        self.SelectPredBtn = QtGui.QPushButton(self.PredBox)
        self.SelectPredBtn.setGeometry(QtCore.QRect(30, 20, 114, 32))
        self.SelectPredBtn.setObjectName(_fromUtf8("SelectPredBtn"))
        self.PredBtn = QtGui.QPushButton(self.PredBox)
        self.PredBtn.setEnabled(False)
        self.PredBtn.setGeometry(QtCore.QRect(180, 20, 114, 32))
        self.PredBtn.setObjectName(_fromUtf8("PredBtn"))
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.ClearBtn, QtCore.SIGNAL(_fromUtf8("clicked()")), self.MsgTxt.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Regression Ridge", None))
        self.MsgLbl.setText(_translate("MainWindow", "messages", None))
        self.FichierGroup.setTitle(_translate("MainWindow", "Fichiers", None))
        self.TrainBtn.setText(_translate("MainWindow", "Choisir Fichier", None))
        self.TestBtn.setText(_translate("MainWindow", "Choisir Fichier", None))
        self.TestLbl.setText(_translate("MainWindow", "Test Set", None))
        self.TrainLbl.setText(_translate("MainWindow", "Train Set", None))
        self.TraceBox.setTitle(_translate("MainWindow", "Tracer", None))
        self.TraceMinTxt.setText(_translate("MainWindow", "1", None))
        self.TraceMinLbl.setText(_translate("MainWindow", "min", None))
        self.TraceMaxLbl.setText(_translate("MainWindow", "max", None))
        self.TraceMaxTxt.setText(_translate("MainWindow", "20", None))
        self.TracePasLbl.setText(_translate("MainWindow", "pas", None))
        self.TracePasTxt.setText(_translate("MainWindow", "1", None))
        self.TraceBtn.setText(_translate("MainWindow", "tracer", None))
        self.LogTraceBox.setTitle(_translate("MainWindow", "Tracer Logarithmique", None))
        self.LTBtn.setText(_translate("MainWindow", "tracer", None))
        self.LTDixPuisTxt.setText(_translate("MainWindow", "3", None))
        self.LTdixPuisLbl.setText(_translate("MainWindow", "10^", None))
        self.modeleBox.setTitle(_translate("MainWindow", "Modele", None))
        self.PredefBRBtn.setText(_translate("MainWindow", "Utiliser b predefini", None))
        self.OptimiseBRBtn.setText(_translate("MainWindow", "Optimiser b", None))
        self.BTxt.setText(_translate("MainWindow", "6", None))
        self.label_5.setText(_translate("MainWindow", "max", None))
        self.label_6.setText(_translate("MainWindow", "min", None))
        self.BMinTxt.setText(_translate("MainWindow", "1", None))
        self.BMaxTxt.setText(_translate("MainWindow", "20", None))
        self.IntervalTxt.setText(_translate("MainWindow", "0.1", None))
        self.label_7.setText(_translate("MainWindow", "+/-", None))
        self.ModelBtn.setText(_translate("MainWindow", "Creer modele", None))
        self.ResBtn.setText(_translate("MainWindow", "Tracer residus", None))
        self.statsBtn.setText(_translate("MainWindow", "statistiques", None))
        self.ClearBtn.setText(_translate("MainWindow", "clear", None))
        self.PredBox.setTitle(_translate("MainWindow", "Prediction", None))
        self.SelectPredBtn.setText(_translate("MainWindow", "Choisir Fichier", None))
        self.PredBtn.setText(_translate("MainWindow", "Predir", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))

